---
title: "EA1_ND_SF"
author: "Sandra Fogg & Natalie Dornan"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
## Load packages

library(tidyverse)
library(dplyr)
library(devtools)
```

```{r, include=FALSE}
#Create data frames containing the original data
og_df <- read_csv("HW1 Data.csv") 
  # mutate("weights" = (runif(484, 0, 1))) %>%
  # mutate("cba" = (weights*shark_suitability + (1-weights)*tuna_suitability)/cost_of_pixel)
og_df


shark_df <- og_df %>% 
  select(pixel, cost_of_pixel, shark_suitability, tuna_suitability)

tuna_df <- og_df %>% 
  select(pixel, cost_of_pixel, tuna_suitability, shark_suitability)
```

Appendix I.
```{r}

### Part B ###

#Arrange dataframes by cost to find the best suitability pixels by cost

shark_suit_df <- shark_df %>% 
  mutate("suit_per_unit_cost" = shark_suitability/cost_of_pixel) %>% 
  arrange(-suit_per_unit_cost) %>%
  mutate("cum_sum" = cumsum(cost_of_pixel)) %>%
  filter(cum_sum <200)

shark_suit_df

```

```{r, include=FALSE}

##solve for alpha##

alpha_shark <- 1/(sum(og_df$shark_suitability)^0.6)

alpha_tuna <- 1/(sum(og_df$tuna_suitability)^0.6)

#find the probability of survival for both species even when sharks are sole concern

prob_shark <- alpha_shark*(sum(shark_suit_df$shark_suitability)^0.6)


prob_tuna <- alpha_tuna*(sum(shark_suit_df$tuna_suitability)^0.6)

```


```{r}

### PART C ###

##Tuna are sole concern

#Arrange dataframes by cost to find the best suitability pixels by cost
tuna_suit_df <- tuna_df %>% 
  mutate("suit_per_unit_cost" = tuna_suitability/cost_of_pixel) %>% 
  arrange(-suit_per_unit_cost) %>%
  mutate("cum_sum" = cumsum(cost_of_pixel)) %>%
  filter(cum_sum <200)

tuna_suit_df

```


```{r, include=FALSE}

### PART D ###
## Create 10 random reserve networks that you can afford within your budget. Show probability performance on a figure. 

reserve.random = data.frame()
rando.probs = data.frame()

for (i in 1:10) {
  reserve.random = og_df[sample(1:nrow(og_df)),] %>%
       mutate("cum_sum" = cumsum(cost_of_pixel)) %>%
       filter(cum_sum <200) 
  
  rando.probs[i,1] = alpha_shark*(sum(reserve.random$shark_suitability)^0.6)
  rando.probs[i,2] = alpha_tuna*(sum(reserve.random$tuna_suitability)^0.6)

}

print(sum(reserve.random$shark_suitability))

ggplot(rando.probs, aes(V1,V2)) +
  geom_point() +
  theme_bw() +
  labs(x = "Shark Survival Probability", y = "Tuna Survival Probablility", title = "Shark vs. Tuna Survival Probabilities for 10 Random Reserves")


```

Appendix II.
```{r}
ggplot(rando.probs, aes(V1,V2)) +
  geom_point() +
  theme_bw() +
  labs(x = "Shark Survival Probability", y = "Tuna Survival Probablility", title = "Shark vs. Tuna Survival Probabilities for 10 Random Reserves")
```


```{r, include=FALSE}

### PART E ###

##for loop i in whatever weights you want for a function you create for the probability calculation

survival <- data.frame()

survival_weight <- function(w) {
  
  og_df$cba <- (w*og_df$shark_suitability + (1-w)*og_df$tuna_suitability)/og_df$cost_of_pixel
  
  x <- og_df %>%
    arrange(desc(cba)) %>%
    mutate(cum_sum = cumsum(cost_of_pixel)) %>%
    filter(cum_sum <200)
  
  survival[1,1] <- alpha_shark*(sum(x$shark_suitability)^0.6)
  survival[1,2] <- alpha_tuna*(sum(x$tuna_suitability)^0.6)
  
  return(survival)
  
}

## for loop

weights <- seq(0,1,0.01)

solution <- lapply(weights, survival_weight)

df <- data.frame()

for (i in 1:101) {
  df[i,1] <- solution[[i]]$V1
  df[i,2] <- solution[[i]]$V2
}


# weight.random <- data.frame()
# survival_weight <- data.frame()
# 
# 
# for (i in 1:100) {
#   weight.random = og_df[sample(1:nrow(og_df)),] %>%
#         
#         mutate("cum_sum" = cumsum(cost_of_pixel)) %>%
#         filter(cum_sum <200) 
#   
#   survival_weight[i,1] = alpha_shark*(sum(weight.random$cba)^0.6)
#   survival_weight[i,2] = alpha_tuna*(sum(weight.random$cba)^0.6)
# 
# }
# 
# 
ggplot(df, aes(V1,V2)) +
  geom_point() +
  geom_smooth(method = "auto", se = FALSE) +
  theme_bw() +
  labs(x = "Shark Survival Probability", y = "Tuna Survival Probablility", title = "Shark vs. Tuna Efficiency Frontier Curve")

 



```

Appendix III.
```{r}

### Frontier Curve Plot ###

ggplot(df, aes(V1,V2)) +
  geom_point() +
  geom_smooth(method = "auto", se = FALSE) +
  theme_bw() +
  labs(x = "Shark Survival Probability", y = "Tuna Survival Probablility", title = "Shark vs. Tuna Efficiency Frontier Curve")

```


